version: '3'

services:

  wordpress:
    image: wordpress
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: example
    working_dir: /var/www/html
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    ports:
      - "127.0.0.3:8080:80"
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
